# Generated by Django 5.0.2 on 2024-03-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='image',
            new_name='gallery',
        ),
    ]
