# Generated by Django 5.0.2 on 2024-03-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image_articlepage_gallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='introduction',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='subtitle',
        ),
    ]
