# Generated by Django 5.0.3 on 2024-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericSiteContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Linkedin URL')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp Url')),
                ('business_address', models.CharField(blank=True, max_length=100, verbose_name='Business Address')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='Business Email')),
                ('business_phone', models.CharField(blank=True, max_length=15, verbose_name='Telephone Number')),
                ('business_workhours', models.CharField(blank=True, max_length=100, verbose_name='Working Hours')),
                ('footer_description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('footer_copyright_notice', models.CharField(blank=True, max_length=40, verbose_name='Company Name')),
                ('whatsapp_title', models.CharField(blank=True, max_length=30, verbose_name='Texto Llamada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
