# Generated by Django 5.0.3 on 2024-03-07 07:42

import CGL.base.block
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('Carousel_Section', wagtail.blocks.StructBlock([('slider', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('description', wagtail.blocks.TextBlock(required=False)), ('gallery', wagtail.images.blocks.ImageChooserBlock(required=False)), ('page_link_title_standard', wagtail.blocks.CharBlock(required=False)), ('page_link', wagtail.blocks.PageChooserBlock(required=False)), ('page_link_title_secondary', wagtail.blocks.CharBlock(required=False)), ('page_link_2', wagtail.blocks.PageChooserBlock(required=False))]), required=True))])), ('About_Section', wagtail.blocks.StructBlock([('about_title', wagtail.blocks.CharBlock(required=False)), ('about_block', wagtail.blocks.RichTextBlock(icon='pilcrow', required=False, template='blocks/paragraph_block.html')), ('gallery', wagtail.images.blocks.ImageChooserBlock(required=False)), ('link_title', wagtail.blocks.TextBlock(required=False)), ('link_page', wagtail.blocks.PageChooserBlock(required=False))])), ('Clean_Section', wagtail.blocks.StructBlock([('about_title', wagtail.blocks.CharBlock(required=False)), ('about_block', wagtail.blocks.StreamBlock([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media', template='blocks/embed_block.html'))], required=False))])), ('Services_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(CGL.base.block.ServiceParallaxBlock, required=False))])), ('QuickLinks_Section', wagtail.blocks.StructBlock([('featured_page_1_title', wagtail.blocks.TextBlock(required=False)), ('page_1_description', wagtail.blocks.CharBlock(required=False)), ('page_1', wagtail.blocks.PageChooserBlock(required=False)), ('featured_page_2_title', wagtail.blocks.TextBlock(required=False)), ('page_2_description', wagtail.blocks.CharBlock(required=False)), ('page_2', wagtail.blocks.PageChooserBlock(required=False)), ('featured_page_3_title', wagtail.blocks.TextBlock(required=False)), ('page_3_description', wagtail.blocks.CharBlock(required=False)), ('page_3', wagtail.blocks.PageChooserBlock('wagtailcore.Page', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', verbose_name='Featured Page 3')), ('featured_page_4_title', wagtail.blocks.TextBlock(required=False)), ('page_4_description', wagtail.blocks.CharBlock(required=False)), ('page_4', wagtail.blocks.PageChooserBlock(required=False))])), ('Contact_Section', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('phone', wagtail.blocks.CharBlock(required=False)), ('suggestion', wagtail.blocks.CharBlock(required=False))])), ('BlogSection', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('select_specific_blog', wagtail.blocks.PageChooserBlock(required=False))]))], blank=True, use_json_field=True, verbose_name='Home Body'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
