# Generated by Django 5.0.2 on 2024-03-04 20:28

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatespage',
            name='body',
            field=wagtail.fields.StreamField([('CertificateSearch', wagtail.blocks.StructBlock([('searchengine', wagtail.blocks.CharBlock(required=False))]))], blank=True, use_json_field=True, verbose_name='Structure Builder'),
        ),
        migrations.AddField(
            model_name='certificatespage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
