# Generated by Django 5.0.2 on 2024-03-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_tablex_autogenerated_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablex',
            name='autogenerated_id',
        ),
        migrations.AddField(
            model_name='tablex',
            name='custom_nomenclature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
