# Generated by Django 5.0.2 on 2024-03-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_remove_tablex_autogenerated_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableX',
        ),
    ]
