# Generated by Django 5.0.2 on 2024-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_delete_tablex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
