# Generated by Django 5.0.2 on 2024-03-06 17:30

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_listofcertificates_lister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateslist',
            name='main',
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='item_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='item_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre General'),
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='lister',
            field=wagtail.fields.StreamField([('Table_Generator', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), required=True)), ('description', wagtail.blocks.StreamBlock([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media', template='blocks/embed_block.html'))], required=False))]))], blank=True, use_json_field=True, verbose_name='Generador de Tablas'),
        ),
    ]
