# Generated by Django 5.0.2 on 2024-03-06 17:44

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_remove_certificateslist_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcertificates',
            name='item_title',
            field=models.CharField(blank=True, help_text='Puede usar la siguiente nomenclatura: CGL-[AÑO]-[LETRA INICIAL TIPO JOYA ej. D = diamante M=moneda]-NNNNN_(id registro) debería tener el siguiente ejemplo: CGL-24-D00001', max_length=255, null=True, verbose_name='Nombre General'),
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='lister',
            field=wagtail.fields.StreamField([('Table_Generator', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), required=True)), ('heading', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))], required=False))]))], blank=True, use_json_field=True, verbose_name='Generador de Tablas'),
        ),
    ]
