# Generated by Django 5.0.2 on 2024-03-06 17:47

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0017_alter_listofcertificates_lister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcertificates',
            name='lister',
            field=wagtail.fields.StreamField([('Table_Generator', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), required=True)), ('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('textfield', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, use_json_field=True, verbose_name='Generador de Tablas'),
        ),
    ]
