# Generated by Django 5.0.2 on 2024-03-06 21:37

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0019_alter_listofcertificates_lister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcertificates',
            name='item_id',
            field=models.CharField(blank=True, help_text='Puede usar la siguiente nomenclatura: CGL-[AÑO]-[LETRA INICIAL TIPO JOYA ej. D = diamante M=moneda]-NNNNN_(id registro) debería tener el siguiente ejemplo: CGL-24-D00001', max_length=30, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='item_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre General'),
        ),
        migrations.AlterField(
            model_name='listofcertificates',
            name='lister',
            field=wagtail.fields.StreamField([('Table_Content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('textfield', wagtail.blocks.RichTextBlock(required=False))])), ('Table_Images', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), required=False))]))], blank=True, use_json_field=True, verbose_name='Generador de Tablas'),
        ),
    ]
