# Generated by Django 5.0.2 on 2024-03-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0020_alter_listofcertificates_item_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOfCertificates',
        ),
    ]
