# Generated by Django 5.0.2 on 2024-03-06 22:54

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0021_delete_listofcertificates'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateslist',
            name='body',
            field=wagtail.fields.StreamField([('Table_Generator', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=255, required=False)), ('textfield', wagtail.blocks.RichTextBlock(required=False))])), ('Image_Inserter', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='certificateslist',
            name='date_published',
            field=models.DateField(blank=True, null=True, verbose_name='Date of publication: '),
        ),
        migrations.AddField(
            model_name='certificateslist',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
