# Generated by Django 5.0.2 on 2024-03-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0023_alter_certificatespage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateslist',
            name='cert_id_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateslist',
            name='date_pub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
