# Generated by Django 5.0.3 on 2024-03-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0024_certificateslist_cert_id_title_and_more'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateslist',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
